name: Generate GitHub Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            output/github-contribution-grid-snake.svg?palette=github-dark&color_snake=%23ff4fae&color_dots=%231b1024,%23351a40,%236d2a68,%23b94d9c,%23ff8bd2

      - name: Push snake animation to output branch
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BUILD_DIR: output
